/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.com.jenkins;

import static org.junit.Assert.*;

import org.junit.Test;

import main.java.com.jenkins.App;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
