/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JunitTest;

public class Library {
	int a;
	int b;
	public int add(int a,int b) {
		return a+b;
	}
	public static void main(String[] args) {
		Library lib=new Library();
		lib.add(lib.a,lib.b);
	}
}
