/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JunitTest;

import  org.junit.Assert.*;

import static org.junit.Assert.*;

import org.junit.Test;

public class LibraryTest {
	@Test 
	public void testSomeLibraryMethod() {
		Library library = new Library();
		assertEquals(26,10+16);
	}
	@Test 
	public void testLibraryMethod() {
		Library library = new Library();
		assertEquals(0,16-16);
	}
}
